name: Metrics
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          user: TheApexWu
          template: classic
          config_timezone: America/New_York

          base: header, activity, repositories
          base_indepth: yes
          base_hireable: no

          repositories_skipped: TheApexWu

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_ignored: Jupyter Notebook, HTML, CSS, Shell
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_notable: yes
          plugin_notable_repositories: yes

          config_order: base.header, isocalendar, base.activity, base.repositories, languages
